{
 "title": "Endpoint Overview",
 "time": { "from": "now-25y", "to": "now+24h" },
 "templating": {
  "list": [
   {
    "name": "var_endpoint",
    "label": "Endpoint",
    "query": "select distinct(endpoint) from endpoint;"
   },
   {
    "name": "var_os_version",
    "label": "Operating System",
    "query": "select distinct(os_version) from endpoint;"
   },
   {
    "name": "var_ps_version",
    "label": "PS Version",
    "query": "select distinct(ps_version) from endpoint;"
   },
   {
    "name": "var_ad_site",
    "label": "AD Site",
    "query": "select distinct(coalesce(ad_site, \"None\")) from endpoint;"
   },
   {
    "name": "var_ad_dc",
    "label": "Domain Controller",
    "query": "select distinct(coalesce(ad_dc, \"None\")) from endpoint ;"
   },
   {
    "name": "var_ad_domain",
    "label": "Domain",
    "query": "select distinct(coalesce(ad_domain, \"None\")) from endpoint;"
   },
   {
    "name": "var_computer_role",
    "label": "Computer Role",
    "query": "select distinct(computer_role) from endpoint where computer_role != \"\";"
   },
   {
    "name": "var_ipsubnet",
    "label": "IP Subnet",
    "query": "select distinct(ipsubnet) from endpoint;"
   }
  ]
 },
 "panels": [
  {
   "title": "Booting timeline",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  SUBSTRING(os_boottime,1,11) as day,\n  count(endpoint_id) as \"Endpoints booted\"\nFROM endpoint\nWHERE\n  $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP by day\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  endpoint AS metric,\n  count(endpoint_id) AS \"Endpoints\"\nFROM endpoint \nWHERE $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Endpoint Overview",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  created_at as \"First Seen\",\n  ts as \"Last Seen\",\n  os_boottime as \"Last Boot\",\n  endpoint as \"Endpoint\",\n  coalesce(ps_version, \"None\") as \"PS Version\",\n  coalesce(dotnet_version, \"None\") as \".Net Version\",\n  coalesce(os_version, \"None\") as \"Operation System\",\n  coalesce(ipv4, \"None\") as \"IP Address\",\n  coalesce(ipsubnet, \"None\") as \"Subnet\",\n  coalesce(os_language, \"None\") as \"OS Language\",\n  coalesce(os_architecture, \"None\") as \"Architecture\",\n  coalesce(timezone, \"None\") as \"UTC Offset\",\n  coalesce(ad_site, \"None\") as \"AD Site\",\n  coalesce(ad_dc, \"None\") as \"Domain Controller\",\n  coalesce(ad_domain, \"None\") as \"Domain\",\n  coalesce(computer_role, \"None\")  as \"Role\"\nfrom endpoint\nWHERE $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet;"
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  os_architecture AS metric,\n  count(os_architecture) as Architecture\nFROM endpoint\nWHERE\n  $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY os_architecture\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "PowerShell Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(ps_version, \"None\") AS metric,\n  count(ps_version) as \"PowerShell Version\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY ps_version\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "Operating Systems",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  os_version AS metric,\n  count(os_version) as \"Operation System\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY os_version\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "AD Domain",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(ad_domain, \"None\") AS metric,\n  count(coalesce(ad_domain, \"None\")) as \"AD Domain\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY ad_domain\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "Subnet",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(ipsubnet, \"None\") AS metric,\n  count(coalesce(ipsubnet, \"None\")) as \"IP Subnet\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY ipsubnet\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": ".Net Version",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(dotnet_version, \"None\") AS metric,\n  count(dotnet_version) as \".Net Version\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY dotnet_version\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "AD Site",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(ad_site, \"None\") AS metric,\n  count(coalesce(ad_site, \"None\")) as \"AD Site\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY ad_site\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "Endpoint Role",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(computer_role, \"None\") AS metric,\n  count(computer_role) as \"Endpoint Role\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY computer_role\nORDER BY os_boottime"
    }
   ]
  },
  {
   "title": "Domain controller",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  os_boottime AS \"time\",\n  coalesce(ad_dc, \"None\") AS metric,\n  count(coalesce(ad_dc, \"None\")) as \"AD Domain\"\nFROM endpoint\nWHERE\n    $__timeFilter(os_boottime) and endpoint like $var_endpoint and os_version like $var_os_version and ps_version like $var_ps_version and computer_role like $var_computer_role and coalesce(ad_site, \"None\") like $var_ad_site and coalesce(ad_dc, \"None\") like $var_ad_dc and coalesce(ad_domain, \"None\") like $var_ad_domain and coalesce(ipsubnet, \"None\") like $var_ipsubnet\nGROUP BY ad_dc\nORDER BY os_boottime"
    }
   ]
  }
 ]
}