{
 "title": "Log4J Overview",
 "time": { "from": "now-25y", "to": "now+24h" },
 "templating": {
  "list": [
   {
    "name": "var_endpoint",
    "label": "Endpoint",
    "query": "select distinct(endpoint) from log4j_master;"
   },
   {
    "name": "var_log4j_version",
    "label": "Log4J Version",
    "query": "select distinct(jar_file) from log4j_master where jar_file like \"%core%\";"
   },
   {
    "name": "var_log4j_level",
    "label": "Log4J Level",
    "query": "Critical : \"core(.*?)[^1.]2(?!\\.1[5-9]\\.)\" , Medium : \"core.*?[^1.]2\\.1[56]\", Patched : \"core.*?[^1\\.]2\\.[1-2]{1}[7-9]{1}\", Outdated : \"[^2.]1\\.[0-9]{1}[0-9]?\", Unknown : \"^((?!(1|2)).)*$\""
   }
  ]
 },
 "panels": [
  {
   "title": "Critical Findings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  path as \"path\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file REGEXP \"core(.*?)[^1.]2(?!\\.1[5-9]\\.)\"\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "Medium Findings (V2.1[56])",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file REGEXP \"core.*?[^1.]2\\.1[56]\"\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "Patched Findings (V2.17)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file REGEXP \"core.*?[^1\\.]2\\.[1-2]{1}[7-9]{1}\"\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "Scope (log4j-core)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file like $var_log4j_version and jar_file like \"%core%\"\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "All Log4J Jar Files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "Findings Overview:  $var_log4j_level",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  endpoint as Endpoint,\n  jar_file as \"Log4J Version\",\n  path as \"Location\",\n  finding_ts AS \"Timestamp\"\nFROM log4j_master\nWHERE $__timeFilter(finding_ts) AND endpoint LIKE $var_endpoint and jar_file REGEXP ${var_log4j_level:value}\n"
    }
   ]
  },
  {
   "title": "All Log4J Jar Files",
   "type": "table",
   "gridPos": { "h": 24, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  endpoint as Endpoint,\n  jar_file as \"Log4J Version\",\n  path as \"Location\",\n  finding_ts AS \"Timestamp\"\nFROM log4j_master\nWHERE $__timeFilter(finding_ts) AND endpoint LIKE $var_endpoint AND jar_file LIKE $var_log4j_version\n"
    }
   ]
  },
  {
   "title": "Unknown Findings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file REGEXP \"^((?!(1|2)).)*$\"\nGROUP BY \"Jar Files\""
    }
   ]
  },
  {
   "title": "Core Version Overview: $var_log4j_level",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  jar_file as \"Version\",\n  count(jar_file) as \"Findings\"\nFROM log4j_master\nWHERE $__timeFilter(finding_ts) AND endpoint LIKE $var_endpoint AND jar_file LIKE $var_log4j_version and jar_file REGEXP $var_log4j_level and jar_file like \"%core%\"\nGROUP BY jar_file order by Findings desc limit 25\n"
    }
   ]
  },
  {
   "title": "Outdated Findings (V1.X)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  jar_file AS metric,\n  count(jar_file) AS \"Jar Files\"\nFROM log4j_master\n  WHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and jar_file REGEXP \"[^2.]1\\.[0-9]{1}[0-9]?\"\nGROUP BY \"Jar Files\""
    }
   ]
  }
 ]
}