{
 "title": "SpyDR Overview",
 "time": { "from": "now-25y", "to": "now+24h" },
 "templating": {
  "list": [
   {
    "name": "var_endpoint",
    "label": "Endpoint",
    "query": "select distinct(endpoint) from master;"
   },
   {
    "name": "var_category",
    "label": "Category",
    "query": "select distinct(category) from master;"
   },
   {
    "name": "var_rule",
    "label": "Rule",
    "query": "select distinct(rule) from master;"
   },
   {
    "name": "var_severity",
    "label": "Severity",
    "query": "select distinct(severity) from master;"
   },
   {
    "name": "var_finding",
    "label": "Finding",
    "query": "select distinct(REPLACE(finding, '\\\\', '\\\\\\\\')) from master;"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<img src=\"https://github.com/hiddenobjects/pub/blob/main/images/hidden_objects_white.png?raw=true\"/>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  arp_id\nFROM arp_cache\nWHERE\n  $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(finding_ts,1d),\n  count(finding) AS \"Findings\"\nFROM master\nWHERE\n  $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY 1\nORDER BY $__timeGroup(finding_ts,1d)"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  severity AS metric,\n  count(severity) AS \"Severity\"\nFROM master\nWHERE severity = \"High\" and $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY severity,2\n"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  severity AS metric,\n  count(severity) AS \"Severity\"\nFROM master\nWHERE severity = \"Medium\" and $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY severity,2\n"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  severity AS metric,\n  count(severity) AS \"Severity\"\nFROM master\nWHERE severity = \"Low\" and $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY severity,2\n"
    }
   ]
  },
  {
   "title": "Findings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  count(endpoint) AS \"Endpoint\"\nFROM master\nWHERE\n  $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')"
    }
   ]
  },
  {
   "title": "Affected Endpoints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(endpoint)) AS \"Endpoints\"\nFROM master\nWHERE $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')"
    }
   ]
  },
  {
   "title": "All Endpoints",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ts AS \"time\",\n  endpoint AS metric,\n  count(endpoint_id) AS \"Endpoints\"\nFROM endpoint \nWHERE $__timeFilter(ts)\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table",
   "gridPos": { "h": 10, "w": 2, "x": 12, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  endpoint AS \"Endpoint\",\n  count(finding) as \"Findings\"\nFROM master\nWHERE $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY endpoint\nORDER BY Findings desc\n"
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "table",
   "gridPos": { "h": 10, "w": 3, "x": 14, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  os_version AS \"Operating System\",\n  count(distinct endpoint) as \"Endpoints\"\nFROM master\nWHERE $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\ngroup by os_version\nORDER BY Endpoints desc\n"
    }
   ]
  },
  {
   "title": "Findings",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 17, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  finding as Finding,\n  count(finding) as \"Findings\"\nfrom master\nWHERE $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\ngroup by finding\norder by Findings desc\n"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  category AS metric,\n  count(category) AS \"category\"\nFROM master\nWHERE\n  $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY category,2\nORDER BY finding_ts"
    }
   ]
  },
  {
   "title": "Rules",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  rule AS metric,\n  count(rule) AS \"Rule\"\nFROM master\nWHERE\n  $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nGROUP BY rule,2\nORDER BY finding_ts"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 15, "w": 23, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  endpoint AS \"Endpoint\",\n  finding AS \"Finding\",\n  details AS \"Details\",\n  category AS \"Category\",\n  rule AS \"Rule\",\n  severity AS \"Severity\",\n  os_version AS \"OS\",\n  finding_ts AS \"Timestamp\"\nFROM master\nWHERE $__timeFilter(finding_ts) and category like $var_category and endpoint like $var_endpoint and rule like $var_rule and severity like $var_severity and finding like REPLACE($var_finding,'\\\\','\\\\\\\\')\nORDER BY finding_ts DESC"
    }
   ]
  }
 ]
}