{
 "title": "User Hunt",
 "time": { "from": "now-25y", "to": "now+24h" },
 "templating": {
  "list": [
   {
    "name": "var_user_rule",
    "label": "Username",
    "query": "select distinct(user_rule) from user_master;"
   },
   {
    "name": "var_category",
    "label": "Category",
    "query": "select distinct(category) from user_master;"
   },
   {
    "name": "var_endpoint",
    "label": "Endpoint",
    "query": "select distinct(endpoint) from user_master;"
   }
  ]
 },
 "panels": [
  {
   "title": "Timeline Findings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(finding_ts,$__interval),\n  count(finding) AS \"Finding\"\nFROM user_master\nWHERE\n  $__timeFilter(finding_ts) and endpoint like $var_endpoint and user_rule like $var_user_rule and category like $var_category\nGROUP BY 1\nORDER BY $__timeGroup(finding_ts,$__interval)"
    }
   ]
  },
  {
   "title": "Users",
   "type": "table",
   "gridPos": { "h": 31, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(user_rule) as Users,\n  count(finding_ts) as Findings\nFROM user_master\nWHERE user_rule like $var_user_rule and endpoint like $var_endpoint and category like $var_category and $__timeFilter(finding_ts)\ngroup by Users\norder by Findings desc"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table",
   "gridPos": { "h": 31, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  distinct(endpoint) as Endpoints,\n  count(finding_ts) as Findings\nFROM user_master\nWHERE endpoint like $var_endpoint and user_rule like $var_user_rule and category like $var_category and $__timeFilter(finding_ts)\ngroup by Endpoints\norder by Findings desc"
    }
   ]
  },
  {
   "title": "Findings on Endpoints",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  endpoint AS metric,\n  count(endpoint) AS \"Endpoints\"\nFROM user_master\nwhere user_rule like $var_user_rule and endpoint like $var_endpoint and category like $var_category and $__timeFilter(finding_ts)\nORDER BY finding_ts\n\n"
    }
   ]
  },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  category AS metric,\n  count(category) AS \"category\"\nFROM user_master\nWHERE user_rule like $var_user_rule and endpoint like $var_endpoint and category like $var_category and $__timeFilter(finding_ts)\nGROUP BY category,2\nORDER BY finding_ts"
    }
   ]
  },
  {
   "title": "User Activity Findings",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  finding_ts AS \"time\",\n  user_rule AS metric,\n  count(distinct(user_rule)) AS \"Users\"\nFROM user_master\nwhere user_rule like $var_user_rule and endpoint like $var_endpoint and category like $var_category and $__timeFilter(finding_ts)\nORDER BY finding_ts\n\n"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT\n  endpoint as Endpoint,\n  category as Category,\n  origin as User_Source,\n  user_rule as User,\n  finding as Finding,\n  details as Details,\n  severity as Severity,\n  finding_ts as Timestamp\nFROM user_master\nWHERE endpoint like $var_endpoint and user_rule like $var_user_rule and category like $var_category and $__timeFilter(finding_ts)\norder by user_rule"
    }
   ]
  }
 ]
}